# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python CI
# Triggerd the workflow on any push to the main branch or pull request.
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]


jobs:
  build:

    runs-on: ubuntu-latest
    #step 1
    steps:
    - name: Chech out code
      uses: actions/Checkout@2
     #step 2
    - name: Set up Python
      uses: actions/setup-python@2
      with:
      python-version: "3.8"
      #step 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
     #step 4   
    - name: Run tests
      run: |
        pytest
